# Generated by Django 3.0.7 on 2020-06-26 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('restaurant', models.CharField(max_length=20)),
                ('numberOfPeople', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 26, 15, 56, 34, 507299))),
            ],
        ),
    ]
