# Generated by Django 3.0.7 on 2020-06-26 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=100)),
                ('expense', models.CharField(max_length=100)),
                ('offers', models.CharField(max_length=100)),
                ('waitTime', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
