# Generated by Django 3.0.7 on 2020-06-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200626_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'get_latest_by': 'waitTime'},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
