# Generated by Django 3.0.7 on 2020-06-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200627_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('itemPrice', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
